apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-application
  namespace: systems
spec:
  syncPolicy:
    automated:
      selfHeal: true
  project: dev-project
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    targetRevision: dev
    repoURL: git@github.com:longersoft/k8s-devops.git
    path: chart/application
    # helm:
    #   valueFiles:
    #     - "values.yaml" # | "values.dev.yaml"
