apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-secrets-store
  namespace: infrastructure
spec:
  project: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    targetRevision: dev
    repoURL: git@github.com:longersoft/k8s-devops.git
    path: chart/infrastructure/secrets-store-csi-driver
