{{- define "common.secret-provider-class" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "common.fullname" . }}
spec:
  provider: aws
  secretObjects:
    {{- toYaml .Values.secretProviderClass.secretObjects | nindent 4 }}
  parameters:
    {{- toYaml .Values.secretProviderClass.parameters | nindent 4 }}
{{- end }}
