{{- define "common.configuration.secret" }}
{{- if .Values.configuration.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.global.common.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData: 
{{- range $key, $value :=  .Values.configuration.secrets }}
    {{ $key }}: |-
{{- tpl $value $ | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
