on:
  workflow_call:
    secrets:
      AWS_ENV_VARIABLES:
        required: true
    inputs:
      work-directory:
        type: string
        required: true
      aws-region:
        type: string
        required: false

jobs:
  TerraformApply:
    runs-on: ubuntu-latest
    name: Terraform Apply
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: arn:aws:iam::012345678910:role/GitHubAction-AssumeRoleWithAction
      #     role-session-name: GitHub_to_AWS_via_FederatedOIDC
      #     aws-region: ${{ input.aws-region }}

      # - name: Sts GetCallerIdentity
      #   run: |
      #     aws sts get-caller-identity

      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: terraform_plan
          path: ./infrastructure/${{ inputs.work-directory }}

      - name: Terraform Apply
        working-directory: ./infrastructure/${{ inputs.work-directory }}
        run: |
          # Remove this block while the block config aws get un-commented
          echo "${{ secrets.AWS_ENV_VARIABLES }}" > aws_env_variables.sh
          chmod +x aws_env_variables.sh && source ./aws_env_variables.sh
          export AWS_REGION=${{ inputs.aws-region }}

          terraform init
          terraform apply ${{ github.run_id }}-plan.out
